phrases=["Breathe in courage, exhale fear",
    "Dream big, dare greatly.",
    "Live, love, laugh endlessly.",
    "Create your own sunshine.",
    "Spread kindness like confetti.",
    "Stay wild, moon child.",
    "Keep your soul on fire.",
    "Believe in the magic within.",
    "Work hard. Dream big.",
    "Be a voice not an echo.",
    "You are your only limit.",
    "Wait and see.",
    "Money often costs too much.",
    "Cherish the moments.",
    "Imagination rules the world.",
    "Nobody’s perfect, but me.",
    "Never look back.",
    "Every solution breeds new problems.",
    "Everything you can imagine is real.",
    "Success doesn’t come to you…you go to it.",
    "Those who cannot change their minds cannot change anything.",
    "Being entirely honest with oneself is a good exercise.",
    "A day without laughter is a day wasted.",
    "Everything happens for a reason.",
    "If you never try you will never know.",
    "It’s never too late to be what you might have been.",
    "Some people are poor, all they have is money.",
    "In simplicity, there’s beauty.",
    "Nature does not hurry, yet everything is accomplished.",
    "The universe dances in whispers.",
    "Seek beauty in every soul.",
    "Let your heart be your masterpiece.",
    "Poetry is in the air, breathe it in.",
    "Life is a canvas, paint your dreams.",
    "Live without regrets.",
    "Follow your heart.",
    "My life – my rules."]